// Static, English-authored menu structure — section order, item order, and
// price never change per locale (see the i18n plan: "price/structure stay
// as-is"). Section/item counts and order here MUST match
// dictionaries/*/menu.json's food/beverage sections exactly (positional
// merge via lib/menuLocalization.js's localizeMenuSections). Also the
// single source `menu/food/page.js` and `menu/beverage/page.js` build their
// JSON-LD from, and that home/MenuHighlight.js's curated highlights are
// looked up against by English name (see FOOD_HOMEPAGE_HIGHLIGHTS in
// signatureMenu.js).
export const FOOD_SECTIONS = [
  {
    title: "Appetizer",
    items: [
      { name: "Vegetables Spring Roll", desc: "Fried roll filled with mixed vegetables, served with sweet & sour sauce", price: "55K" },
      { name: "Tomato Bruschetta", desc: "Baguette, tomato, basil, onion, olive oil, fetta cheese & balsamic vinegar", price: "65K" },
      { name: "Garlic Bread", desc: "Baguette, toasted with garlic butter", price: "65K" },
      { name: "Garden Salad", desc: "Mixed lettuce, onion, cucumber and carrot with balsamic vinaigrette", price: "75K" },
      { name: "Caesar Salad", desc: "Baby romain lettuce, crispy bacon, garlic bread and caesar dressing", price: "95K" },
      { name: "Thai Beef Salad", desc: "Served with mixed salad and thai dressing", price: "95K" },
      { name: "Smoked Salmon Salad", desc: "Served with mini mesclun and chili lime dressing", price: "95K" },
    ],
  },
  {
    title: "Soups",
    items: [
      { name: "Cream Corn Soup", desc: "Thick soup with sweet corn and garlic bread", price: "65K" },
      { name: "Chicken Vegetable Soup", desc: "Clear soup with diced chicken, carrot, onion, and green bean", price: "55K" },
      { name: "Seafood Cream Soup", desc: "Mixed seafood, cream, served with garlic bread", price: "75K" },
      { name: "Tom Yum Soup", desc: "Spicy prawn, fish, squid, and slice mushroom", price: "75K" },
      { name: "Chicken Noodle Soup", desc: "Sliced chicken leg, vegetables, chicken stock, egg noodle", price: "55K" },
    ],
  },
  {
    title: "Our Signature",
    items: [
      { name: "Mr Bob's BBQ Ribs", desc: "Our finest well marinated 600 gr Baby Back Pork Ribs, slow charcoal grilled with honey and Mr Bob's sauce", price: "215K" },
      { name: "Beef Tomahawk", desc: "1000-1200 gr grilled Australian beef tomahawk served with three kinds of sauce (BBQ, mushroom and black pepper), mixed salad, sauteed vegetables and potato wedges. Suitable for 2 pax; takes around 60 minutes to prepare.", price: "950K" },
    ],
  },
  {
    title: "Side Dish",
    items: [
      { name: "Steamed Rice", price: "20K" },
      { name: "Pineapple Rice", price: "30K" },
      { name: "Corn Rice", price: "30K" },
      { name: "Mixed Salad", price: "30K" },
      { name: "Potatoes Wedges", price: "30K" },
      { name: "Mashed Potatoes", price: "30K" },
      { name: "French Fries", price: "30K" },
      { name: "Sauteed Vegetables", price: "30K" },
    ],
  },
  {
    title: "Indonesian",
    items: [
      { name: "Beef Rendang", desc: "Dices of beef stewed in Indonesian style served with steamed rice", price: "145K" },
      { name: "Seafood Curry", desc: "Prawn, fish and squid, mixed vegetables braised with curry sauce", price: "140K" },
      { name: "Chicken Curry", desc: "Sliced chicken breast and mixed vegetables braised with curry sauce", price: "110K" },
      { name: "Ayam Betutu", desc: "Braised half baby chicken served with sayur urab and steamed rice", price: "110K" },
      { name: "Bebek Goreng", desc: "Crispy half fried duck served with vegetables curry and steamed rice", price: "120K" },
      { name: "Nasi Goreng Seafood", desc: "Fried rice, prawn, fish, squid, prawn satay and crackers", price: "130K" },
      { name: "Nasi Goreng Ayam / Mie Goreng Ayam", desc: "Fried rice or noodle with egg, chicken satay and crackers", price: "100K" },
      { name: "Nasi Goreng Iga Bakar", desc: "Fried rice with egg, pork ribs and crackers", price: "140K" },
      { name: "Nasi Goreng Crispy Pork Belly", desc: "Fried rice with egg and pork belly", price: "140K" },
      { name: "Beef Paela", desc: "Grilled sirloin steak and prawn on yellow rice", price: "190K" },
      { name: "Cap Cay Ayam / Cap Cay Seafood", desc: "Stir fry chicken or seafood and vegetables Chinese style, served with steamed rice", price: "100K / 130K" },
    ],
  },
  {
    title: "Grill Corner: Poultry",
    items: [
      { name: "Grill Chicken Leg Boneless", desc: "200 gr grilled chicken leg boneless, honey chili sauce, served with sambal matah and steamed rice", price: "100K" },
      { name: "Grill Baby Chicken", desc: "Half grilled baby chicken with Balinese spice, served with steamed rice, sambal matah and sayur urab", price: "110K" },
      { name: "Chicken Satay", desc: "8 pcs grilled chicken satay, served with peanut sauce and steamed rice", price: "110K" },
      { name: "Chicken Steak", desc: "Grilled 200 gr chicken breast served with mashed potatoes, sauteed vegetables and mushroom cream sauce", price: "110K" },
      { name: "Chicken Cordon Bleu", desc: "Chicken breast stuffed with ham and cheese, served with mashed potatoes, sauteed vegetables and mushroom cream sauce", price: "110K" },
    ],
  },
  {
    title: "Grill Corner: Seafood",
    items: [
      { name: "Grill Lobster", desc: "350 gr grilled lobster served with mixed salad, mashed potatoes, mustard cream sauce, and lemon butter sauce", price: "450K" },
      { name: "Grill Prawn", desc: "5 pcs selected grilled king prawn, served with lemon butter, honey chili sauce, mixed salad and mashed potatoes", price: "170K" },
      { name: "Grill Snapper", desc: "350 gr grilled whole baby white snapper served with sambal matah and steamed rice", price: "140K" },
      { name: "Salmon Steak", desc: "200 gr pan seared salmon steak served with mixed vegetables, mashed potatoes, honey chili and lemon butter sauce", price: "210K" },
      { name: "Grill Mahi-Mahi Fillet", desc: "200 gr grilled mahi-mahi fish served with mixed salad, lemon butter, honey chili sauce, and mashed potatoes", price: "140K" },
      { name: "Seafood Basket (for two)", desc: "Grilled 1 pc lobster, 5 pcs king prawn, 2 pcs mahi-mahi steak, 1 pc squid, served with mixed salad, french fries or steamed rice, and 3 kinds of sauce (lemon butter, sambal matah, honey chili). Includes 2 small Bintang beers.", price: "850K" },
    ],
  },
  {
    title: "Grill Corner: Meat (Beef & Lamb)",
    items: [
      { name: "Tenderloin Steak", desc: "200 gr grilled beef tenderloin served with black pepper and mushroom sauce, sauteed vegetables and french fries", price: "195K" },
      { name: "Sirloin Steak", desc: "200 gr grilled beef sirloin served with mushroom sauce, black pepper sauce, sauteed vegetables and french fries", price: "175K" },
      { name: "Rib Eye Steak", desc: "200 gr grilled beef rib eye served with mushroom sauce, black pepper sauce, sauteed vegetables and french fries", price: "185K" },
      { name: "Grilled Beef Kebab", desc: "Grilled diced beef with red pepper, green pepper, and onion on skewer, served with mushroom, black pepper sauce and potato wedges", price: "195K" },
      { name: "Lamb Steak", desc: "200 gr grilled lamb served with mushroom sauce, black pepper sauce, sauteed vegetables and french fries", price: "205K" },
      { name: "Lamb Satay", desc: "10 pcs lamb satay served with steamed rice and peanut sauce", price: "170K" },
      { name: "Surf and Turf", desc: "Grilled 200 gr tenderloin steak topped with prawn, served with mini mesclun, potato wedges, mushroom sauce and BBQ sauce", price: "220K" },
    ],
  },
  {
    title: "Grill Corner: Meat (Pork)",
    items: [
      { name: "Pork Knuckle (for two)", desc: "1.1kg deep fried pork knuckle served with mashed potatoes, sauteed vegetables, bean sauce, and pork gravy", price: "800K" },
      { name: "Grill Pork Chop", desc: "350 gr grilled pork chop served with BBQ sauce, black pepper sauce, sauteed vegetables and french fries", price: "220K" },
      { name: "Grill Pork Steak", desc: "200 gr grilled pork steak served with BBQ sauce, black pepper sauce, sauteed vegetables and french fries", price: "150K" },
      { name: "Pork Satay", desc: "10 pcs grilled pork satay with steamed rice and peanut sauce", price: "120K" },
      { name: "Grill Pork Belly Satay", desc: "4 pcs grilled pork belly satay served with steamed rice and hot sweet chili sauce", price: "150K" },
      { name: "Crispy Pork Belly", desc: "Served with sweet chili soya sauce, black bean sauce and steamed rice", price: "170K" },
      { name: "Mixed Grill (for two)", desc: "Grilled 1 pc pork chop, 1/2 portion ribs, 1 pc sirloin steak, 2 pcs lamb medallion, 2 pcs chicken sausage and 2 pcs pork ham, served with mushroom sauce, black pepper sauce, BBQ sauce, mixed salad and potato wedges", price: "900K" },
    ],
  },
  {
    title: "Burger & Sandwich",
    items: [
      { name: "Black Devil", desc: "100 gr Texas beef patty, bacon, homemade chili sauce, egg, cheddar cheese, lettuce, tomato, served with french fries", price: "110K" },
      { name: "White Angel", desc: "100 gr imported wagyu patty, bacon, egg, cheddar cheese, lettuce, tomato, Bob's burger sauce, served with french fries", price: "110K" },
      { name: "Chicken Sandwich", desc: "Toast, chicken, cheese, tomato, lettuce, served with french fries", price: "90K" },
      { name: "Chicken Ciabatta", desc: "Ciabatta bread, chicken, cheese, tomato, lettuce, served with french fries", price: "100K" },
      { name: "Club Sandwich", desc: "Toast, tomato, bacon, egg, cheese, lettuce, served with french fries", price: "100K" },
      { name: "Smoked Salmon Sandwich", desc: "Toast, smoked salmon, lettuce, tomato and cheese, served with french fries", price: "100K" },
    ],
  },
  {
    title: "Pizza & Pasta",
    items: [
      { name: "Margarita Pizza", desc: "Tomato concasse and mozzarella cheese", price: "95K" },
      { name: "Pizza Sambal Matah", desc: "Tomato concasse, shredded chicken and mozzarella cheese", price: "110K" },
      { name: "Pizza Ayam Betutu", desc: "Tomato concasse, shredded chicken, betutu spice and mozzarella cheese", price: "110K" },
      { name: "Hawaiian Pizza", desc: "Tomato concasse, diced chicken, diced pineapple and mozzarella cheese", price: "110K" },
      { name: "Meat Lover Pizza", desc: "Tomato concasse, beef chorizo, ham, salami, and mozzarella cheese", price: "140K" },
      { name: "BBQ Chicken Pizza", desc: "Tomato concasse, BBQ chicken, mixed bell pepper, onion and mozzarella cheese", price: "130K" },
      { name: "Spaghetti Marinara", desc: "Mixed seafood, tomato concasse, basil, parmesan cheese", price: "140K" },
      { name: "Spaghetti Bolognaise", desc: "Minced beef, tomato concasse, basil, parmesan cheese", price: "140K" },
      { name: "Spaghetti Carbonara", desc: "Bacon, cream, parsley, parmesan cheese", price: "140K" },
      { name: "Fettuccine Alfredo", desc: "Spaghetti with mushroom, ham, cream sauce and parmesan cheese", price: "140K" },
      { name: "Spaghetti Napolitana", desc: "Spaghetti with tomato sauce and parmesan cheese", price: "90K" },
      { name: "Spaghetti Aglio Olio", desc: "Sauteed spaghetti with olive oil, sliced garlic, hot chili, parmesan cheese", price: "90K" },
      { name: "Spaghetti Aglio Olio with Grilled Prawn", desc: "Sauteed spaghetti with olive oil, sliced garlic, hot chili, 3 pcs grilled prawn and parmesan cheese", price: "130K" },
    ],
  },
  {
    title: "Bob's Junior",
    note: "Kids menu",
    items: [
      { name: "Fish & Chips", desc: "Served with tartar sauce & thousand island sauce", price: "80K" },
      { name: "Calamari Ring", desc: "Served with tartar sauce & thousand island sauce", price: "80K" },
      { name: "Spaghetti Napolitana", desc: "Spaghetti with tomato sauce and parmesan cheese", price: "70K" },
      { name: "Spaghetti Aglio Olio", desc: "Sauteed spaghetti with olive oil and chopped garlic", price: "70K" },
      { name: "Mac & Cheese", desc: "Mixed macaroni and cheese in cream sauce, topped with grated parmesan cheese and sliced ham", price: "95K" },
      { name: "Chicken Nugget", desc: "3 pcs chicken nugget and french fries", price: "70K" },
      { name: "Nasi Goreng Sausage", desc: "Fried rice served with grilled sausage and prawn crackers", price: "80K" },
      { name: "Mini Burger", desc: "White bun, beef patty, egg, cheese, lettuce, served with french fries", price: "80K" },
    ],
  },
  {
    title: "Dessert",
    items: [
      { name: "Banana Split", desc: "3 scoops of ice cream and sliced banana", price: "75K" },
      { name: "Apple Pie", desc: "Australian style apple pie served with vanilla ice cream", price: "75K" },
      { name: "Tiramisu", price: "75K" },
      { name: "Chocolate Cake", desc: "Served with chocolate sauce", price: "75K" },
      { name: "Ice Cream Selection", desc: "3 scoops of vanilla, strawberry, or chocolate flavor", price: "60K" },
      { name: "Slice Tropical Fresh Fruit", desc: "Sliced watermelon, papaya, and pineapple", price: "60K" },
      { name: "Chocolate Brownies", desc: "Served with 1 scoop vanilla ice cream", price: "75K" },
    ],
  },
];

export const BEVERAGE_SECTIONS = [
  {
    title: "Classic Cocktail",
    note: "Premium Spirit 135K / Local Spirit 100K",
    items: [
      { name: "Margarita", desc: "Tequila, orange liqueur, fresh lime" },
      { name: "Mojito's", desc: "Rum, fresh lime, sprig of mint leaf" },
      { name: "Daiquiry's", desc: "Rum, orange liqueur, fresh lime" },
      { name: "Espresso Martini", desc: "Vodka, coffee liqueur, espresso" },
      { name: "Lychee Martini", desc: "Vodka, lychee liqueur, lychee fruit" },
      { name: "Caipirinha & Caipiroska", desc: "Rum/vodka, fresh lime, sweetener" },
      { name: "Long Island Ice Tea", desc: "Vodka, rum, gin, tequila, triple sec, lime, topped with Coke" },
      { name: "Pinacolada", desc: "Light rum, pineapple, coconut milk, coconut liqueur" },
      { name: "Old Fashioned", desc: "Bourbon whiskey, simple syrup, angostura bitter" },
      { name: "Negroni", desc: "Gin, campari, sweet vermouth" },
      { name: "Lemon Drop", desc: "Vodka, lemon juice, orange liqueur" },
      { name: "Dry or Sweet Martini", desc: "Dry gin, dry or sweet vermouth" },
      { name: "Whiskey Sour", desc: "Whiskey, lime juice, sugar" },
      { name: "Japanese Slipper", desc: "Vodka, lime juice, triple sec, melon liqueur" },
      { name: "Pink/White/Blue Lady", desc: "Gin, orange liqueur, lime juice, grenadine or blue curacao" },
      { name: "Tequila Sunrise", desc: "Tequila, orange juice, grenadine" },
      { name: "White or Black Russian", desc: "Vodka, coffee liqueur, cream" },
      { name: "Cosmopolitan", desc: "Vodka, triple sec, cranberry juice, lime juice" },
      { name: "Long Beach", desc: "Vodka, orange juice, cranberry juice" },
    ],
  },
  {
    title: "Bob's Cocktails (Signature)",
    note: "120K",
    items: [
      { name: "Bob's Bitter Sweet", desc: "White rum, campari, pineapple juice, passion syrup" },
      { name: "Bob's Negroni", desc: "Campari, cherry water, sweet vermouth" },
      { name: "Tropical Gin", desc: "Gin, strawberry, lime, mint leaf, sugar, topped with tonic water" },
      { name: "Flower Bloom", desc: "Gin, lime juice, cananga syrup, soda water" },
      { name: "Bloody Orange", desc: "Vodka, orange juice, fresh strawberry, lime juice, simple syrup" },
      { name: "Bob's Sangria", desc: "Spiced arak, red/white wine, tropical fruit" },
      { name: "Mango Basil Daiquiry", desc: "White rum, mango juice, triple sec, basil leaf, lime juice" },
      { name: "Watermelon Mexico", desc: "Tequila, orange liqueur, lime juice, watermelon, passion syrup" },
      { name: "Bob Penicillin", desc: "Whisky, fresh lemon juice, lemongrass honey syrup" },
      { name: "Nusa Dua Colada", desc: "White rum, pineapple liqueur, pineapple juice, mango juice, coconut cream, blue syrup" },
    ],
  },
  {
    title: "Spirits by Shot",
    note: "45ml",
    items: [
      { name: "Gin", desc: "Bombay Sapphire", price: "100K" },
      { name: "Vodka", desc: "Absolut", price: "100K" },
      { name: "Rum", desc: "Bacardi, Captain Morgan", price: "100K" },
      { name: "Tequila", desc: "Jose Cuervo", price: "100K" },
      { name: "Scotch Whiskey", desc: "Red Label, Black Label", price: "100K" },
      { name: "American Whiskey", desc: "Jack Daniel, Jim Beam", price: "100K" },
      { name: "Irish Whiskey", desc: "John Jameson", price: "100K" },
    ],
  },
  {
    title: "Bob's Refreshing",
    items: [
      { name: "Shirley Temple", desc: "Cherry water, grenadine, lime juice, topped with sprite", price: "70K" },
      { name: "Hera's Crown", desc: "Orange juice, grenadine, lemon juice, topped with sprite", price: "70K" },
      { name: "Mint Sensation", desc: "Lychee, pineapple, mint leaf", price: "70K" },
      { name: "Mango Frappe", desc: "Mango puree/juice, orange juice, lime juice, tonic water", price: "70K" },
      { name: "Berry Sunshine", desc: "Strawberry, pineapple juice, orange juice, simple syrup", price: "70K" },
      { name: "Lychee Basilia", desc: "Lychee fruit, basil leaf, sweet sour, sprite", price: "70K" },
      { name: "Tiki Berry", desc: "Fresh strawberry, pineapple juice, passion syrup, coconut cream and lemon juice", price: "70K" },
      { name: "Lemon Lime Bitter", desc: "Lime juice, lemon juice, simple syrup, angostura bitter, soda water", price: "65K" },
      { name: "Lemon Up (Pink/Blue/Natural)", desc: "Fresh lemon juice, lemonade, simple syrup, grenadine/blue syrup", price: "60K" },
      { name: "Queenchers (Strawberry/Mango)", desc: "Lemon juice, mango/strawberry puree, lemonade, simple syrup", price: "60K" },
    ],
  },
  {
    title: "Beer's",
    items: [
      { name: "Bintang", desc: "Large / Small", price: "70K / 50K" },
      { name: "Bintang Radler", price: "50K" },
      { name: "Crystal Bintang", price: "55K" },
      { name: "Heineken", desc: "Large / Small", price: "75K / 55K" },
      { name: "Balihai", desc: "Large / Small", price: "75K / 55K" },
      { name: "Singaraja", price: "35K" },
      { name: "Prost Pilsner / Lager", price: "40K" },
      { name: "Albens Apple Cider", price: "60K" },
      { name: "Tower Bintang", price: "200K" },
      { name: "Tower Balihai", price: "215K" },
      { name: "Tower Heineken", price: "215K" },
    ],
  },
  {
    title: "Soft Drinks & Water",
    items: [
      { name: "Coke", price: "20K" },
      { name: "Coke Zero", price: "20K" },
      { name: "Sprite", price: "20K" },
      { name: "Fanta", price: "20K" },
      { name: "Tonic Water", price: "20K" },
      { name: "Soda Water", price: "20K" },
      { name: "Ginger Ale", price: "20K" },
      { name: "Natural Water", price: "25K" },
      { name: "Sparkling Water", price: "35K" },
    ],
  },
  {
    title: "Milkshake & Smoothies",
    items: [
      { name: "Vanilla", price: "55K" },
      { name: "Chocolate", price: "55K" },
      { name: "Banana", price: "55K" },
      { name: "Mango", price: "55K" },
      { name: "Strawberry", price: "55K" },
    ],
  },
  {
    title: "Coffee & Tea's",
    items: [
      { name: "Balinese Coffee", price: "25K" },
      { name: "Regular Tea", price: "35K" },
      { name: "Lychee Tea", price: "35K" },
      { name: "Passion Tea", price: "35K" },
      { name: "Lemon Grass Tea", price: "35K" },
      { name: "Mint Ginger Tea", price: "35K" },
    ],
  },
  {
    title: "Juices",
    items: [
      { name: "Watermelon", price: "50K" },
      { name: "Pineapple", price: "50K" },
      { name: "Mango", price: "50K" },
      { name: "Orange", price: "50K" },
      { name: "Mix Juice", price: "50K" },
      { name: "Papaya", price: "50K" },
      { name: "Lemon", price: "50K" },
      { name: "Banana", price: "50K" },
      { name: "Lime", price: "50K" },
      { name: "Fresh Coconut", price: "50K" },
    ],
  },
  {
    title: "White Wine",
    note: "By the glass (85K)",
    items: [
      { name: "Two Island Sauvignon Blanc", price: "85K" },
      { name: "Two Island Pinot Grigio", price: "85K" },
      { name: "Two Island Chardonnay", price: "85K" },
      { name: "Two Island Riesling", price: "85K" },
    ],
  },
  {
    title: "Red Wine",
    note: "By the glass (85K)",
    items: [
      { name: "Two Island Cabernet Merlot", price: "85K" },
      { name: "Two Island Shiraz", price: "85K" },
      { name: "Two Island Pinot Noir", price: "85K" },
    ],
  },
  {
    title: "Rosé Wine",
    note: "By the glass (85K)",
    items: [{ name: "Two Island Rose", price: "85K" }],
  },
];
